/* The following code was generated by JFlex 1.4.3 on 11/11/13 1:33 PM */

package biosimilarity.slmc.ast.parsing;
import java_cup.runtime.*;
import biosimilarity.slmc.ast.sr.ParseError;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/11/13 1:33 PM from the specification file
 * <tt>/Users/specialk/Desktop/SLMC-Scala/src/main/java/biosimilarity/slmc/ast/parsing/lexer.lex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\15\1\14\1\13"+
    "\5\16\1\61\1\62\1\5\1\16\1\63\1\16\1\55\1\4\1\7"+
    "\11\6\1\16\1\64\1\47\1\50\1\51\1\54\1\60\32\12\1\52"+
    "\1\16\1\53\1\65\1\11\1\16\1\24\1\10\1\33\1\32\1\22"+
    "\1\23\1\10\1\35\1\31\1\45\1\43\1\25\1\37\1\34\1\30"+
    "\1\42\1\44\1\20\1\26\1\17\1\21\1\27\1\41\1\36\1\40"+
    "\1\10\1\56\1\46\1\57\1\16\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\22\6\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\3\0\1\32\23\6"+
    "\1\33\1\6\1\34\1\35\1\36\3\6\1\37\1\40"+
    "\11\6\1\41\1\42\2\6\1\43\1\44\1\45\1\46"+
    "\1\47\2\0\1\50\2\6\1\51\5\6\1\52\5\6"+
    "\1\53\6\6\1\54\1\6\1\55\3\6\1\56\1\57"+
    "\10\6\1\60\1\0\1\2\1\61\1\6\1\62\1\63"+
    "\1\6\1\64\6\6\1\65\1\66\1\6\1\67\1\6"+
    "\1\70\5\6\1\71\7\6\1\72\1\73\1\74\3\6"+
    "\1\75\1\76\7\6\1\77\1\6\1\100\4\6\1\101"+
    "\1\102\1\6\1\103\1\6\1\104\1\105\1\106\1\107"+
    "\3\6\1\110\1\111\3\6\1\112\1\6\1\113\1\114"+
    "\6\6\1\115\1\116\1\117\13\6\1\120\1\6\1\121"+
    "\1\122\3\6\1\123\1\124\5\6\1\125\1\126\1\6"+
    "\1\127";

  private static int [] zzUnpackAction() {
    int [] result = new int[253];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\66\0\242\0\66\0\330\0\66"+
    "\0\u010e\0\66\0\u0144\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252"+
    "\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402"+
    "\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2"+
    "\0\u05e8\0\u061e\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\66\0\u0654"+
    "\0\u068a\0\u06c0\0\66\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce"+
    "\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u010e\0\u0af8"+
    "\0\u010e\0\u010e\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u010e\0\u010e"+
    "\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80"+
    "\0\u0db6\0\u010e\0\u010e\0\u0dec\0\u0e22\0\66\0\66\0\u0e58"+
    "\0\66\0\66\0\u0e8e\0\u0ec4\0\66\0\u0efa\0\u0f30\0\u010e"+
    "\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u010e\0\u1074\0\u10aa"+
    "\0\u10e0\0\u1116\0\u114c\0\u010e\0\u1182\0\u11b8\0\u11ee\0\u1224"+
    "\0\u125a\0\u1290\0\u010e\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u139e"+
    "\0\u010e\0\u010e\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2"+
    "\0\u1518\0\u154e\0\66\0\u1584\0\u0e8e\0\u010e\0\u15ba\0\u010e"+
    "\0\u010e\0\u15f0\0\u010e\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe"+
    "\0\u1734\0\u010e\0\u010e\0\u176a\0\u17a0\0\u17d6\0\u010e\0\u180c"+
    "\0\u1842\0\u1878\0\u18ae\0\u18e4\0\u010e\0\u191a\0\u1950\0\u1986"+
    "\0\u19bc\0\u19f2\0\u1a28\0\u1a5e\0\u010e\0\u010e\0\u010e\0\u1a94"+
    "\0\u1aca\0\u1b00\0\u010e\0\u010e\0\u1b36\0\u1b6c\0\u1ba2\0\u1bd8"+
    "\0\u1c0e\0\u1c44\0\u1c7a\0\u010e\0\u1cb0\0\u1ce6\0\u1d1c\0\u1d52"+
    "\0\u1d88\0\u1dbe\0\u010e\0\u010e\0\u1df4\0\u1e2a\0\u1e60\0\u010e"+
    "\0\u010e\0\u010e\0\u010e\0\u1e96\0\u1ecc\0\u1f02\0\u010e\0\u010e"+
    "\0\u1f38\0\u1f6e\0\u1fa4\0\u010e\0\u1fda\0\u010e\0\u010e\0\u2010"+
    "\0\u2046\0\u207c\0\u20b2\0\u20e8\0\u211e\0\u010e\0\u010e\0\u010e"+
    "\0\u2154\0\u218a\0\u21c0\0\u21f6\0\u222c\0\u2262\0\u2298\0\u22ce"+
    "\0\u2304\0\u233a\0\u2370\0\u010e\0\u23a6\0\u010e\0\u010e\0\u23dc"+
    "\0\u2412\0\u2448\0\u010e\0\u010e\0\u247e\0\u24b4\0\u24ea\0\u2520"+
    "\0\u2556\0\u010e\0\u010e\0\u258c\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[253];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\4\1\2\1\16\1\17"+
    "\1\11\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\11\1\34\2\11"+
    "\1\35\1\11\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\70\0\1\4\67\0\1\60"+
    "\1\61\66\0\2\7\64\0\5\11\4\0\27\11\26\0"+
    "\5\13\4\0\27\13\24\0\7\62\1\0\52\62\50\0"+
    "\1\63\23\0\5\11\4\0\1\11\1\64\3\11\1\65"+
    "\10\11\1\66\10\11\26\0\5\11\4\0\3\11\1\67"+
    "\23\11\26\0\5\11\4\0\6\11\1\70\1\11\1\71"+
    "\4\11\1\72\1\11\1\73\7\11\26\0\5\11\4\0"+
    "\1\11\1\74\3\11\1\75\3\11\1\76\15\11\26\0"+
    "\5\11\4\0\6\11\1\77\6\11\1\100\11\11\26\0"+
    "\5\11\4\0\11\11\1\101\1\102\14\11\26\0\5\11"+
    "\4\0\3\11\1\103\12\11\1\104\3\11\1\105\4\11"+
    "\26\0\5\11\4\0\11\11\1\106\15\11\26\0\5\11"+
    "\4\0\1\11\1\107\2\11\1\110\10\11\1\111\11\11"+
    "\26\0\5\11\4\0\4\11\1\112\10\11\1\113\11\11"+
    "\26\0\5\11\4\0\3\11\1\114\23\11\26\0\5\11"+
    "\4\0\6\11\1\115\2\11\1\116\1\11\1\117\1\120"+
    "\1\11\1\121\10\11\26\0\5\11\4\0\3\11\1\122"+
    "\5\11\1\123\15\11\26\0\5\11\4\0\3\11\1\124"+
    "\6\11\1\125\14\11\26\0\5\11\4\0\5\11\1\126"+
    "\4\11\1\127\14\11\26\0\5\11\4\0\1\11\1\130"+
    "\3\11\1\131\4\11\1\132\1\133\13\11\26\0\5\11"+
    "\4\0\2\11\1\134\24\11\26\0\5\11\4\0\11\11"+
    "\1\135\15\11\66\0\1\136\1\0\1\137\65\0\1\140"+
    "\65\0\1\141\1\142\14\0\1\60\1\3\1\4\63\60"+
    "\5\143\1\144\60\143\13\0\1\145\60\0\5\11\4\0"+
    "\2\11\1\146\2\11\1\147\21\11\26\0\5\11\4\0"+
    "\2\11\1\150\24\11\26\0\5\11\4\0\3\11\1\151"+
    "\6\11\1\152\14\11\26\0\5\11\4\0\10\11\1\153"+
    "\16\11\26\0\5\11\4\0\7\11\1\154\17\11\26\0"+
    "\5\11\4\0\3\11\1\155\23\11\26\0\5\11\4\0"+
    "\13\11\1\156\13\11\26\0\5\11\4\0\12\11\1\157"+
    "\14\11\26\0\5\11\4\0\3\11\1\160\23\11\26\0"+
    "\5\11\4\0\6\11\1\161\20\11\26\0\5\11\4\0"+
    "\1\11\1\162\25\11\26\0\5\11\4\0\22\11\1\163"+
    "\4\11\26\0\5\11\4\0\13\11\1\164\13\11\26\0"+
    "\5\11\4\0\5\11\1\165\21\11\26\0\5\11\4\0"+
    "\7\11\1\166\17\11\26\0\5\11\4\0\6\11\1\167"+
    "\20\11\26\0\5\11\4\0\11\11\1\170\15\11\26\0"+
    "\5\11\4\0\12\11\1\171\14\11\26\0\5\11\4\0"+
    "\12\11\1\172\14\11\26\0\5\11\4\0\4\11\1\173"+
    "\22\11\26\0\5\11\4\0\7\11\1\174\17\11\26\0"+
    "\5\11\4\0\4\11\1\175\22\11\26\0\5\11\4\0"+
    "\3\11\1\176\23\11\26\0\5\11\4\0\15\11\1\177"+
    "\11\11\26\0\5\11\4\0\3\11\1\200\23\11\26\0"+
    "\5\11\4\0\22\11\1\201\4\11\26\0\5\11\4\0"+
    "\1\202\26\11\26\0\5\11\4\0\6\11\1\203\20\11"+
    "\26\0\5\11\4\0\13\11\1\204\13\11\26\0\5\11"+
    "\4\0\17\11\1\205\7\11\26\0\5\11\4\0\15\11"+
    "\1\206\11\11\26\0\5\11\4\0\11\11\1\207\15\11"+
    "\26\0\5\11\4\0\1\11\1\210\25\11\26\0\5\11"+
    "\4\0\12\11\1\211\14\11\26\0\5\11\4\0\12\11"+
    "\1\212\14\11\71\0\1\213\14\0\5\143\1\214\64\143"+
    "\1\215\1\214\60\143\6\0\5\11\4\0\3\11\1\216"+
    "\23\11\26\0\5\11\4\0\14\11\1\217\12\11\26\0"+
    "\5\11\4\0\15\11\1\220\11\11\26\0\5\11\4\0"+
    "\7\11\1\221\17\11\26\0\5\11\4\0\3\11\1\222"+
    "\23\11\26\0\5\11\4\0\3\11\1\223\23\11\26\0"+
    "\5\11\4\0\15\11\1\224\11\11\26\0\5\11\4\0"+
    "\7\11\1\225\17\11\26\0\5\11\4\0\7\11\1\226"+
    "\17\11\26\0\5\11\4\0\7\11\1\227\17\11\26\0"+
    "\5\11\4\0\5\11\1\230\21\11\26\0\5\11\4\0"+
    "\5\11\1\231\21\11\26\0\5\11\4\0\13\11\1\232"+
    "\13\11\26\0\5\11\4\0\1\233\26\11\26\0\5\11"+
    "\4\0\3\11\1\234\23\11\26\0\5\11\4\0\22\11"+
    "\1\235\4\11\26\0\5\11\4\0\1\236\26\11\26\0"+
    "\5\11\4\0\13\11\1\237\13\11\26\0\5\11\4\0"+
    "\12\11\1\240\14\11\26\0\5\11\4\0\23\11\1\241"+
    "\3\11\26\0\5\11\4\0\5\11\1\242\21\11\26\0"+
    "\5\11\4\0\1\243\26\11\26\0\5\11\4\0\14\11"+
    "\1\244\12\11\26\0\5\11\4\0\23\11\1\245\3\11"+
    "\26\0\5\11\4\0\13\11\1\246\13\11\26\0\3\11"+
    "\1\247\1\11\4\0\4\11\1\250\22\11\26\0\5\11"+
    "\4\0\4\11\1\251\22\11\26\0\5\11\4\0\14\11"+
    "\1\252\6\11\1\253\3\11\26\0\5\11\4\0\5\11"+
    "\1\254\21\11\26\0\5\11\4\0\1\255\26\11\26\0"+
    "\5\11\4\0\15\11\1\256\11\11\20\0\4\143\1\4"+
    "\1\214\60\143\6\0\5\11\4\0\3\11\1\257\23\11"+
    "\26\0\5\11\4\0\5\11\1\260\21\11\26\0\5\11"+
    "\4\0\1\261\26\11\26\0\5\11\4\0\1\262\26\11"+
    "\26\0\5\11\4\0\16\11\1\263\10\11\26\0\5\11"+
    "\4\0\3\11\1\264\23\11\26\0\5\11\4\0\6\11"+
    "\1\265\20\11\26\0\5\11\4\0\21\11\1\266\5\11"+
    "\26\0\5\11\4\0\14\11\1\267\12\11\26\0\3\11"+
    "\1\270\1\11\4\0\27\11\26\0\5\11\4\0\14\11"+
    "\1\271\12\11\26\0\5\11\4\0\13\11\1\272\13\11"+
    "\26\0\5\11\4\0\1\11\1\273\25\11\26\0\5\11"+
    "\4\0\1\11\1\274\25\11\26\0\5\11\4\0\3\11"+
    "\1\275\23\11\26\0\5\11\4\0\24\11\1\276\2\11"+
    "\26\0\5\11\4\0\3\11\1\277\23\11\26\0\5\11"+
    "\4\0\1\300\26\11\26\0\5\11\4\0\12\11\1\301"+
    "\14\11\26\0\5\11\4\0\12\11\1\302\14\11\26\0"+
    "\5\11\4\0\7\11\1\303\17\11\26\0\5\11\4\0"+
    "\7\11\1\304\17\11\26\0\5\11\4\0\20\11\1\305"+
    "\6\11\26\0\5\11\4\0\6\11\1\306\20\11\26\0"+
    "\5\11\4\0\2\11\1\307\24\11\26\0\5\11\4\0"+
    "\7\11\1\310\17\11\26\0\5\11\4\0\6\11\1\311"+
    "\20\11\26\0\5\11\4\0\7\11\1\312\17\11\26\0"+
    "\5\11\4\0\1\313\26\11\26\0\5\11\4\0\1\314"+
    "\3\11\1\315\2\11\1\316\17\11\26\0\5\11\4\0"+
    "\16\11\1\317\10\11\26\0\5\11\4\0\3\11\1\320"+
    "\23\11\26\0\5\11\4\0\11\11\1\321\15\11\26\0"+
    "\5\11\4\0\17\11\1\322\7\11\26\0\3\11\1\323"+
    "\1\11\4\0\27\11\26\0\5\11\4\0\15\11\1\324"+
    "\11\11\26\0\5\11\4\0\16\11\1\325\10\11\26\0"+
    "\5\11\4\0\17\11\1\326\7\11\26\0\5\11\4\0"+
    "\17\11\1\327\7\11\26\0\5\11\4\0\3\11\1\330"+
    "\23\11\26\0\5\11\4\0\5\11\1\331\21\11\26\0"+
    "\5\11\4\0\5\11\1\332\21\11\26\0\5\11\4\0"+
    "\12\11\1\333\14\11\26\0\5\11\4\0\5\11\1\334"+
    "\21\11\26\0\5\11\4\0\2\11\1\335\24\11\26\0"+
    "\5\11\4\0\14\11\1\336\6\11\1\337\3\11\26\0"+
    "\5\11\4\0\1\340\26\11\26\0\5\11\4\0\14\11"+
    "\1\341\12\11\26\0\5\11\4\0\1\11\1\342\25\11"+
    "\26\0\5\11\4\0\1\343\26\11\26\0\5\11\4\0"+
    "\6\11\1\344\20\11\26\0\5\11\4\0\6\11\1\345"+
    "\20\11\26\0\5\11\4\0\20\11\1\346\6\11\26\0"+
    "\5\11\4\0\12\11\1\347\14\11\26\0\5\11\4\0"+
    "\14\11\1\350\12\11\26\0\5\11\4\0\11\11\1\351"+
    "\15\11\26\0\5\11\4\0\3\11\1\352\23\11\26\0"+
    "\5\11\4\0\3\11\1\353\23\11\26\0\5\11\4\0"+
    "\6\11\1\354\20\11\26\0\5\11\4\0\6\11\1\355"+
    "\20\11\26\0\5\11\4\0\3\11\1\356\23\11\26\0"+
    "\5\11\4\0\6\11\1\357\20\11\26\0\5\11\4\0"+
    "\14\11\1\360\12\11\26\0\5\11\4\0\2\11\1\361"+
    "\24\11\26\0\5\11\4\0\5\11\1\362\21\11\26\0"+
    "\5\11\4\0\1\11\1\363\25\11\26\0\5\11\4\0"+
    "\21\11\1\364\5\11\26\0\5\11\4\0\3\11\1\365"+
    "\23\11\26\0\5\11\4\0\15\11\1\366\11\11\26\0"+
    "\5\11\4\0\13\11\1\367\13\11\26\0\5\11\4\0"+
    "\3\11\1\370\23\11\26\0\5\11\4\0\1\371\26\11"+
    "\26\0\5\11\4\0\7\11\1\372\17\11\26\0\5\11"+
    "\4\0\13\11\1\373\13\11\26\0\5\11\4\0\3\11"+
    "\1\374\23\11\26\0\5\11\4\0\1\11\1\375\25\11"+
    "\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9666];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\30\1\15\11\3\0\1\11\52\1\2\11"+
    "\1\1\2\11\2\0\1\11\45\1\1\11\1\0\161\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[253];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }
  
  public int line() {
    return yyline;
  }
  
  public int column() {
    return yycolumn;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws ParseError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new ParseError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws ParseError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, ParseError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 28: 
          { return symbol(ParserSym.ON);
          }
        case 88: break;
        case 31: 
          { return symbol(ParserSym.CD);
          }
        case 89: break;
        case 80: 
          { return symbol(ParserSym.REVEALALL);
          }
        case 90: break;
        case 87: 
          { return symbol(ParserSym.CC);
          }
        case 91: break;
        case 19: 
          { return symbol(ParserSym.RBR);
          }
        case 92: break;
        case 47: 
          { return symbol(ParserSym.NOT);
          }
        case 93: break;
        case 63: 
          { return symbol(ParserSym.CLEAR);
          }
        case 94: break;
        case 44: 
          { return symbol(ParserSym.OFF);
          }
        case 95: break;
        case 3: 
          { return symbol(ParserSym.STAR);
          }
        case 96: break;
        case 29: 
          { return symbol(ParserSym.IF);
          }
        case 97: break;
        case 79: 
          { return symbol(ParserSym.CTX);
          }
        case 98: break;
        case 72: 
          { return symbol(ParserSym.SWITCH);
          }
        case 99: break;
        case 56: 
          { return symbol(ParserSym.VOID);
          }
        case 100: break;
        case 45: 
          { return symbol(ParserSym.DEFC);
          }
        case 101: break;
        case 18: 
          { return symbol(ParserSym.LBR);
          }
        case 102: break;
        case 33: 
          { return symbol(ParserSym.PI);
          }
        case 103: break;
        case 60: 
          { return symbol(ParserSym.TRACE);
          }
        case 104: break;
        case 8: 
          { return symbol(ParserSym.CAPS_ID, yytext());
          }
        case 105: break;
        case 6: 
          { return symbol(ParserSym.LOWER_ID, yytext());
          }
        case 106: break;
        case 66: 
          { return symbol(ParserSym.PROPS);
          }
        case 107: break;
        case 71: 
          { return symbol(ParserSym.SELECT);
          }
        case 108: break;
        case 42: 
          { return symbol(ParserSym.END);
          }
        case 109: break;
        case 40: 
          { return symbol(ParserSym.FILENAME, yytext());
          }
        case 110: break;
        case 15: 
          { return symbol(ParserSym.RPARR);
          }
        case 111: break;
        case 54: 
          { return symbol(ParserSym.PRINT);
          }
        case 112: break;
        case 52: 
          { return symbol(ParserSym.ELSE);
          }
        case 113: break;
        case 7: 
          { return symbol(ParserSym.USCORE);
          }
        case 114: break;
        case 4: 
          { return symbol(ParserSym.INT, new Integer(yytext()));
          }
        case 115: break;
        case 78: 
          { return symbol(ParserSym.DEFPROP);
          }
        case 116: break;
        case 61: 
          { return symbol(ParserSym.FRESH);
          }
        case 117: break;
        case 25: 
          { return symbol(ParserSym.UPC);
          }
        case 118: break;
        case 39: 
          { return symbol(ParserSym.IMPLIES);
          }
        case 119: break;
        case 34: 
          { return symbol(ParserSym.PD);
          }
        case 120: break;
        case 53: 
          { return symbol(ParserSym.LOAD);
          }
        case 121: break;
        case 14: 
          { return symbol(ParserSym.LPARR);
          }
        case 122: break;
        case 62: 
          { return symbol(ParserSym.FALSE);
          }
        case 123: break;
        case 10: 
          { return symbol(ParserSym.PIPE);
          }
        case 124: break;
        case 24: 
          { return symbol(ParserSym.SEMI);
          }
        case 125: break;
        case 69: 
          { return symbol(ParserSym.FORALL);
          }
        case 126: break;
        case 74: 
          { return symbol(ParserSym.HIDDEN);
          }
        case 127: break;
        case 41: 
          { return symbol(ParserSym.TAU);
          }
        case 128: break;
        case 57: 
          { return symbol(ParserSym.HELP);
          }
        case 129: break;
        case 67: 
          { return symbol(ParserSym.REVEAL);
          }
        case 130: break;
        case 48: 
          { return symbol(ParserSym.EQUIV);
          }
        case 131: break;
        case 5: 
          { return symbol(ParserSym.ZERO);
          }
        case 132: break;
        case 49: 
          { return symbol(ParserSym.TRUE);
          }
        case 133: break;
        case 55: 
          { return symbol(ParserSym.SHOW);
          }
        case 134: break;
        case 86: 
          { return symbol(ParserSym.SHOW_S);
          }
        case 135: break;
        case 13: 
          { return symbol(ParserSym.GT);
          }
        case 136: break;
        case 1: 
          { throw new ParseError(yytext());
          }
        case 137: break;
        case 12: 
          { return symbol(ParserSym.EQ);
          }
        case 138: break;
        case 16: 
          { return symbol(ParserSym.QUESTION);
          }
        case 139: break;
        case 37: 
          { return symbol(ParserSym.DEFARROW);
          }
        case 140: break;
        case 9: 
          { return symbol(ParserSym.BANG);
          }
        case 141: break;
        case 51: 
          { return symbol(ParserSym.THIS);
          }
        case 142: break;
        case 22: 
          { return symbol(ParserSym.RPAR);
          }
        case 143: break;
        case 77: 
          { return symbol(ParserSym.DEFPROC);
          }
        case 144: break;
        case 70: 
          { return symbol(ParserSym.ALWAYS);
          }
        case 145: break;
        case 46: 
          { return symbol(ParserSym.NEW);
          }
        case 146: break;
        case 64: 
          { return symbol(ParserSym.CHECK);
          }
        case 147: break;
        case 68: 
          { return symbol(ParserSym.EXISTS);
          }
        case 148: break;
        case 32: 
          { return symbol(ParserSym.CONV);
          }
        case 149: break;
        case 58: 
          { return symbol(ParserSym.QUIT);
          }
        case 150: break;
        case 11: 
          { return symbol(ParserSym.LT);
          }
        case 151: break;
        case 50: 
          { return symbol(ParserSym.THEN);
          }
        case 152: break;
        case 84: 
          { return symbol(ParserSym.EVENTUALLY);
          }
        case 153: break;
        case 21: 
          { return symbol(ParserSym.LPAR);
          }
        case 154: break;
        case 73: 
          { return symbol(ParserSym.INSIDE);
          }
        case 155: break;
        case 36: 
          { return symbol(ParserSym.SAT);
          }
        case 156: break;
        case 85: 
          { return symbol(ParserSym.MT);
          }
        case 157: break;
        case 83: 
          { return symbol(ParserSym.PARAM);
          }
        case 158: break;
        case 38: 
          { return symbol(ParserSym.DEQ);
          }
        case 159: break;
        case 75: 
          { return symbol(ParserSym.MAXFIX);
          }
        case 160: break;
        case 30: 
          { return symbol(ParserSym.IN);
          }
        case 161: break;
        case 76: 
          { return symbol(ParserSym.MINFIX);
          }
        case 162: break;
        case 2: 
          { /* Ignore */;
          }
        case 163: break;
        case 27: 
          { return symbol(ParserSym.OR);
          }
        case 164: break;
        case 65: 
          { return symbol(ParserSym.PROCS);
          }
        case 165: break;
        case 23: 
          { return symbol(ParserSym.COMMA);
          }
        case 166: break;
        case 35: 
          { return symbol(ParserSym.DBLPIPE);
          }
        case 167: break;
        case 26: 
          { return symbol(ParserSym.NEQ);
          }
        case 168: break;
        case 81: 
          { return symbol(ParserSym.ST);
          }
        case 169: break;
        case 20: 
          { return symbol(ParserSym.FREE);
          }
        case 170: break;
        case 17: 
          { return symbol(ParserSym.DOT);
          }
        case 171: break;
        case 59: 
          { return symbol(ParserSym.JOIN);
          }
        case 172: break;
        case 82: 
          { return symbol(ParserSym.SHOW_F);
          }
        case 173: break;
        case 43: 
          { return symbol(ParserSym.AND);
          }
        case 174: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return symbol(0);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
