
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 11 13:33:50 CST 2013
//----------------------------------------------------

package biosimilarity.slmc.ast.parsing;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int REVEALALL = 10;
  public static final int GT = 60;
  public static final int TRACE = 34;
  public static final int MT = 29;
  public static final int ST = 31;
  public static final int PARAM = 28;
  public static final int CAPS_ID = 84;
  public static final int SEMI = 80;
  public static final int INSIDE = 19;
  public static final int EQUIV = 78;
  public static final int CONV = 45;
  public static final int QUIT = 44;
  public static final int PROPS = 39;
  public static final int COMMA = 73;
  public static final int USCORE = 82;
  public static final int JOIN = 48;
  public static final int CLEAR = 41;
  public static final int LT = 59;
  public static final int DEQ = 75;
  public static final int ALWAYS = 18;
  public static final int DBLPIPE = 70;
  public static final int PROCS = 40;
  public static final int RBR = 68;
  public static final int FALSE = 3;
  public static final int NOT = 6;
  public static final int THEN = 52;
  public static final int TAU = 22;
  public static final int EQ = 74;
  public static final int SAT = 79;
  public static final int SELECT = 5;
  public static final int DEFARROW = 58;
  public static final int PIPE = 56;
  public static final int TRUE = 2;
  public static final int ZERO = 57;
  public static final int LBR = 67;
  public static final int FORALL = 14;
  public static final int QUESTION = 65;
  public static final int EXISTS = 13;
  public static final int LPAR = 71;
  public static final int MAXFIX = 15;
  public static final int SWITCH = 50;
  public static final int STAR = 63;
  public static final int VOID = 4;
  public static final int HIDDEN = 11;
  public static final int ELSE = 53;
  public static final int FILENAME = 85;
  public static final int DOT = 66;
  public static final int LOAD = 42;
  public static final int INT = 86;
  public static final int PI = 46;
  public static final int SHOW = 38;
  public static final int EOF = 0;
  public static final int RPAR = 72;
  public static final int THIS = 54;
  public static final int BANG = 64;
  public static final int PD = 33;
  public static final int PRINT = 37;
  public static final int DEFPROP = 23;
  public static final int FREE = 69;
  public static final int EVENTUALLY = 17;
  public static final int IN = 25;
  public static final int DEFPROC = 26;
  public static final int OR = 8;
  public static final int MINFIX = 16;
  public static final int error = 1;
  public static final int CD = 32;
  public static final int ON = 35;
  public static final int CC = 30;
  public static final int IF = 51;
  public static final int OFF = 36;
  public static final int CTX = 49;
  public static final int END = 55;
  public static final int CHECK = 27;
  public static final int SHOW_S = 21;
  public static final int RPARR = 62;
  public static final int REVEAL = 9;
  public static final int NEW = 24;
  public static final int SHOW_F = 20;
  public static final int DEFC = 47;
  public static final int LOWER_ID = 83;
  public static final int NEQ = 76;
  public static final int FRESH = 12;
  public static final int AND = 7;
  public static final int IMPLIES = 77;
  public static final int HELP = 43;
  public static final int LPARR = 61;
  public static final int UPC = 81;
}

